// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0BG-jaJRh_LLnFI-IZYxVdZWPbAXBd4U',
    appId: '1:853999405886:web:9a74784b800ebe5d723a6f',
    messagingSenderId: '853999405886',
    projectId: 'project-agrichem',
    authDomain: 'project-agrichem.firebaseapp.com',
    storageBucket: 'project-agrichem.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuABRbSkQRe_4RMb6hg32E3h8k8Os6AVY',
    appId: '1:156206724245:android:1b048de82aa601ea2fd79c',
    messagingSenderId: '156206724245',
    projectId: 'interns25-saffronedge-samarth',
    databaseURL: 'https://interns25-saffronedge-samarth-default-rtdb.firebaseio.com',
    storageBucket: 'interns25-saffronedge-samarth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh4aIxOtWGadD7q9DXIsxVJ9qJmvgBv84',
    appId: '1:853999405886:ios:611810822f82f16a723a6f',
    messagingSenderId: '853999405886',
    projectId: 'project-agrichem',
    storageBucket: 'project-agrichem.firebasestorage.app',
    iosBundleId: 'com.example.agriChem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh4aIxOtWGadD7q9DXIsxVJ9qJmvgBv84',
    appId: '1:853999405886:ios:611810822f82f16a723a6f',
    messagingSenderId: '853999405886',
    projectId: 'project-agrichem',
    storageBucket: 'project-agrichem.firebasestorage.app',
    iosBundleId: 'com.example.agriChem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0BG-jaJRh_LLnFI-IZYxVdZWPbAXBd4U',
    appId: '1:853999405886:web:fabda9d0cbb89193723a6f',
    messagingSenderId: '853999405886',
    projectId: 'project-agrichem',
    authDomain: 'project-agrichem.firebaseapp.com',
    storageBucket: 'project-agrichem.firebasestorage.app',
  );
}